services:
  www:
    image: nginx:alpine
    container_name: www
    restart: unless-stopped
    networks:
      - web-traffic
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.www.rule=Host(`testingg.bid`) || Host(`www.testingg.bid`)"
      - "traefik.http.routers.www.entrypoints=websecure"
      - "traefik.http.routers.www.tls.certresolver=myresolver"

networks:
  web-traffic:
    external: true

